### ISSUE TITLE
How can we bypass proxy security on vfsglobal? 

### ISSUE THREAD

**Issue by parmonov98** [vlaim/vfs-check#2]

**Comment by vlaim** [comment]
Hi, for this project there is no proxy support, but it can be easily added. 


The puppeteer has proxy support, it can be passed via arguments: 

```
  const browser = await puppeteer.launch({
    args: [ '--proxy-server=127.0.0.1:9876' ]
  });
  ```

**Comment by parmonov98** [comment]
> Hi, for this project there is no proxy support, but it can be easily added. 
> 
> 
> The puppeteer has proxy support, it can be passed via arguments: 
> 
> ```
>   const browser = await puppeteer.launch({
>     args: [ '--proxy-server=127.0.0.1:9876' ]
>   });
>   ```
> 

 I can't find a good proxy. Can you recommend any?

**Comment by vlaim** [comment]
@parmonov98 for the other project I used https://www.lunaproxy.com/

**Comment by parmonov98** [comment]
> @parmonov98 for the other project I used https://www.lunaproxy.com/

what type of proxy did u use? residential? or somethin else?

**Comment by vlaim** [comment]
@parmonov98 yep, residential

**Comment by parmonov98** [comment]
> @parmonov98 yep, residential

if I order you a bot to monitor for available dates. How much would it be?

**Comment by vlaim** [comment]
@parmonov98 Please kindly check prices here https://www.lunaproxy.com/pay/

The total price will depend on the frequency of checking and amount of nodes. 

Closing this issue for going off topic :)
